<? /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>
<!DOCTYPE html>
<html>
<head>
    <?= $this->headTitle('Росвар Инфо')->setSeparator(' - ') ?>
    <meta charset="UTF-8">
    <?= $this->headMeta() ?>

    <link rel="stylesheet" href="/theme/css/bootstrap.css" type="text/css" media="screen">
    <link rel="stylesheet" href="/theme/css/responsive.css" type="text/css" media="screen">
    <link href="/theme/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/theme/css/theme.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/theme/css/fonts.css" media="screen" rel="stylesheet" type="text/css">

    <?= $this->headLink() ?>
    <!--    <link rel="shortcut icon" href="--><?//= $this->basePath('favicon.ico') ?><!--" />-->
</head>
<body>
<div class="wrapper">
    <!-- Page Header -->
    <header id="masthead">
        <nav class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <h1 class="brand">
                        <a href="<?=$this->url('home')?>">Росвар<span class="light">Инфо</span></a>
                    </h1>
                    <ul class="nav pull-right">
                        <li><a href="<?= $this->url('library/max-stats') ?>">Максимальные статы</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- Main Content -->
    <div id="content" role="main">
        <?=$this->content?>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="comments-form span12 text-center">
                    <h3 class="comment-form small-screen-center">Оставить комментарий</h3>
                    <div id="vk_comments" style="margin: 0 auto;"></div>
                </div>

                <? $this->headScript()->appendFile('//vk.com/js/api/openapi.js?97') ?>
                <? $this->headScript()->appendScript('VK.init({apiId: 3753967, onlyWidgets: true});') ?>
                <? $this->headScript()->appendScript('VK.Widgets.Comments("vk_comments", {limit: 10, width: "520", attach: "photo,video"});') ?>
            </div>
        </div>
    </div>
</div>

<footer id="footer" role="contentinfo">
    <div class="wrapper wrapper-transparent">
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span6 small-screen-center">
                    <h3>
                        Росвар
              <span class="light">
                Инфо
              </span>
                    </h3>
                    <p>
                        contact@roswar.info
                        <br>
                        © Copyright 2013
                    </p>
                </div>
                <div class="span6">
                    <ul class="unstyled inline text-right small-screen-center big social-icons">
                        <li>
                            <a data-iconcolor="#00a0d1" href="#">
                                <i class="icon-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a data-iconcolor="#3b5998" href="#">
                                <i class="icon-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a data-iconcolor="#910101" href="#">
                                <i class="icon-pinterest"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

<? $this->headScript()->prependFile($this->basePath('js/jquery-1.10.1.min.js')) ?>

<?= $this->headScript() ?>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42248528-1', 'roswar.info');
    ga('send', 'pageview');

</script>
</body>
</html>