<?
/**
 * @var $this   \Zend\View\Renderer\PhpRenderer
 * @var $form   \Zend\Form\Form
 * @var $result \Web\Document\FightResult
 */
?>
<? $this->headTitle('Анализатор Стенок') ?>

<style type="text/css">
    .table.winner th {
        border-bottom: 1px solid green;
    }

    .table.winner thead {
        border: 1px solid green;
    }

    .table.looser th {
        border-bottom: 1px solid red;
    }

    .table.looser thead {
        border: 1px solid red;
    }

    .damage-tooltip {
        border-bottom: 1px dashed #567189;
    }
</style>

<section class="section section-padded">
    <div class="container-fluid">
        <div class="section-header">
            <h1>Анализатор Стенок</h1>
        </div>
        <?= $this->form()->openTag($form->prepare()->setAttribute('action', $this->url(null, [], ['fragment' => 'results']))) ?>
        <div class="control-group">
            <label class="control-label" for="url">Ссылка на лог боя</label>

            <div class="controls">
                <div class="input-append">
                    <?= $this->formElement($form->get('url')->setAttribute('class', 'input-xlarge')->setAttribute('id', 'url')) ?>
                    <button type="submit" class="btn btn-primary"><i class="icon-refresh"></i></button>
                </div>
                <?= $this->formElementErrors($form->get('url')) ?>
            </div>
        </div>

        <? if (isset($error) && $error): ?>
            <div class="section">
                <p class="text-error">Стенку такую не найдешь ты.</p>
            </div>
        <? endif; ?>

        <? if (isset($result)): ?>

            <div>
                Результат боя № <a target="_blank" href="http://www.roswar.ru/fight/<?=$result->getId()?>/"><?=$result->getId()?> <i class="icon-external-link"></i></a> <br>
                <?=$result->getDate()->format('H:i:s (Y.m.d)')?>
            </div>

            <div class="row-fluid">
                <div class="span6">
                    <table class="table table-striped table-hover <?=$result->getWinner() == 1 ? 'winner' : 'looser'?>" id="left">
                        <thead>
                        <tr>
                            <th>Ник</th>
                            <th>Урон</th>
                            <th>%</th>
                            <th>Убийств</th>
                            <th>Вылечено</th>
                        </tr>
                        </thead>
                        <tbody>
                        <? foreach ($result->getPlayers(\Web\Document\PlayerStat::TEAM_LEFT) as $player): ?>
                            <tr>
                                <td>
                                    <a target="_blank" href="http://www.roswar.ru/player/<?=$player->getPlayer()->getId()?>/">
                                        <?=$player->getPlayer()->getNickname()?>
                                        <i class="icon-external-link"></i>
                                    </a>
                                </td>
                                <td>
                                    <a class="damage-tooltip" href="javascript:void(0);" data-toggle="tooltip"
                                       title="Урон гранатами: <?=$player->getGrenadeDamage()?>

Брошено гранат: <?=intval($player->getThrows())?>">
                                        <?=$player->getDamage()?>
                                    </a>
                                </td>
                                <td><?=round($player->getPercentage(), 2)?></td>
                                <td><?=$player->getKills()?></td>
                                <td><?=$player->getHealed()?></td>
                            </tr>
                        <? endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <div class="span6">
                    <table class="table table-striped table-hover <?=$result->getWinner() == 2 ? 'winner' : 'looser'?>" id="right">
                        <thead>
                        <tr>
                            <th>Ник</th>
                            <th>Урон</th>
                            <th>%</th>
                            <th>Убийств</th>
                            <th>Вылечено</th>
                        </tr>
                        </thead>
                        <tbody>
                        <? foreach ($result->getPlayers(\Web\Document\PlayerStat::TEAM_RIGHT) as $player): ?>
                            <tr>
                                <td>
                                    <a target="_blank" href="http://www.roswar.ru/player/<?=$player->getPlayer()->getId()?>/">
                                        <?=$player->getPlayer()->getNickname()?>
                                        <i class="icon-external-link"></i>
                                    </a>
                                </td>
                                <td>
                                    <a class="damage-tooltip" href="javascript:void(0);" data-toggle="tooltip"
                                       title="Урон гранатами: <?=$player->getGrenadeDamage()?>

Брошено гранат: <?=intval($player->getThrows())?>">
                                        <?=$player->getDamage()?>
                                    </a>
                                </td>
                                <td><?=round($player->getPercentage(), 2)?></td>
                                <td><?=$player->getKills()?></td>
                                <td><?=$player->getHealed()?></td>
                            </tr>
                        <? endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        <? endif; ?>
        <?= $this->form()->closeTag($form) ?>
    </div>
</section>

<? $this->headLink()->appendStylesheet('/css/dataTables.css') ?>
<? $this->headScript()->appendFile('/js/jquery.dataTables.min.js') ?>

<? $this->headScript()->captureStart() ?>
//<script type="text/javascript">
    (function ($) {
        $.extend( $.fn.dataTableExt.oSort, {
            "num-html-pre": function ( a ) {
                var x = String(a).replace( /<[\s\S]*?>/g, "" );
                return parseFloat( x );
            },

            "num-html-asc": function ( a, b ) {
                return ((a < b) ? -1 : ((a > b) ? 1 : 0));
            },

            "num-html-desc": function ( a, b ) {
                return ((a < b) ? 1 : ((a > b) ? -1 : 0));
            }
        } );

        $('#left, #right').dataTable({
            aaSorting:[[1, 'desc']],
            sDom: '<"section"t>',
            iDisplayLength: 1000,
            aoColumns:[
                null,
                {sType: 'num-html'},
                null,
                null,
                null
            ]
        });
    })(jQuery);
//</script>
<? $this->headScript()->captureEnd() ?>