<!-- Promo Section -->
<section class="section section-alt">
    <div class="row-fluid">
        <div class="super-hero-unit">
            <figure>
                <img alt="some image" src="/theme/img/landscape-3-1250x600.jpg">
                <figcaption class="flex-caption">
                    <h1 class="hyper animated fadeinup delayed">
                        Скоро
                    </h1>
                </figcaption>
            </figure>
        </div>
    </div>
</section>